import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../entities/payment.dart';
import '../repositories/payments_repository.dart';
import '../../data/providers/payments_providers.dart';

class CreatePaymentUseCase {
  final PaymentsRepository _repository;

  CreatePaymentUseCase(this._repository);

  Future<Payment> call({
    required String memberId,
    required String packageId,
    required double amount,
    double discountAmount = 0.0,
    DateTime? dueDate,
    String? scheduleId,
  }) async {
    final payment = Payment(
      id: '', // Will be generated by repository
      memberId: memberId,
      packageId: packageId,
      amount: amount,
      discountAmount: discountAmount,
      status: PaymentStatus.pending,
      dueDate: dueDate,
      createdAt: DateTime.now(),
      scheduleId: scheduleId,
    );

    return await _repository.createPayment(payment);
  }
}

final createPaymentUseCaseProvider = Provider<CreatePaymentUseCase>((ref) {
  final repository = ref.read(paymentsRepositoryProvider);
  return CreatePaymentUseCase(repository);
});
